spring:
  application:
    name: zuul-server

server:
  port: 5555
  servlet:
    context-path: /

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

# http"//localhost:5555[/endpoint/]
zuul:
  routes:
    products-service: /api/v1/products/**
    frontend: /**
  sensitiveHeaders: Cookie, Set-Cookie
