spring:
  application:
    name: products-service
  datasource:
    url: jdbc:h2:mem:products
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 19872

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
